### ISSUE TITLE
History page incorrectly flags breaking changes

### ISSUE THREAD

**Issue by billyjanitsch** [apollographql/apollo-studio-community#65] opened 2021-03-19 22:01 UTC
Starting with this schema:

```graphql
type Dog {
  name: String!
}

type Query {
  dogs: [Dog!]!
}
```

And reporting this new schema:

```graphql
type Dog {
  name: String!
}

type Query {
  dogs: [Dog!]!
}

input CreateDogInput {
  name: String!
}

type Mutation {
  createDog(input: CreateDogInput!): Dog!
}
```

Apollo Studio's History page lists the following as a breaking change:

```
CreateDogInput
Input_object
Addition
name: String!
input type CreateDogInput: non-null field name added.
See NON_NULLABLE_FIELD_ADDED_TO_INPUT_OBJECT documentation for more details.
```

This is incorrect. `NON_NULLABLE_FIELD_ADDED_TO_INPUT_OBJECT` is supposed to represent the addition of a field to an _existing_ input object, but `CreateDogInput` didn't previously exist. There is no possible breaking change here.

I also noticed that Apollo Studio doesn't list a `TYPE_ADDED` change for `CreateDogInput`, so it seems not to be picking up the fact that this is a new type, which may be the root cause of the false positive.

**Comment by pcarrier** [comment] 2022-02-26 00:10
Can you confirm this still occurs?

I couldn't reproduce here, the change doesn't appear as breaking in the variant's ChangeLog:
![image](https://user-images.githubusercontent.com/8641/155819378-1da3b083-323e-4c40-a234-38bac57756a1.png)

Nor in a check for the change:
![studio-staging apollographql com_graph_engine_operationsCheck_b9036c16-2170-42f1-9eea-7bb634640d8b_variant=pcarrier0](https://user-images.githubusercontent.com/8641/155819478-ff6eccaa-363d-4b33-9e08-45d23cec6b6d.png)

and we do get a type added.

**Comment by d3rp3tt3** [comment] 2022-10-07 01:33
Closing this out since it's been quite some time since the issue was originally reported.

**Closed by d3rp3tt3** 2022-10-07 01:33 UTC
