### ISSUE TITLE
Apollo Studio Explorer generates invalid variables for required (non-null) arguments (input fields)

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [apollographql/apollo-studio-community#190] opened 2022-09-06 19:23 UTC
**Context:** https://twitter.com/alexey_rodionov/status/1284118554024050688

![apollo-studio-explorer](https://user-images.githubusercontent.com/7892779/188720377-851b23e7-eef0-482e-8290-f96cfea8e629.png)

**Current behavior:** Apollo Studio Explorer fill outs the `null` value for required (non-null) arguments (input fields) as default variable value.

**Expected behavior:** Apollo Studio Explorer fill outs the `""` for strings, `0` for ints and floats, `[]` for arrays, etc. as default variable value.

**Comment by daniman** [comment] 2022-09-06 21:25
Hey @FluorescentHallucinogen, I believe this is a duplicate of the request in #163 so I'm going to close this issue. 😄   It seems like this is a preference that could go both ways. The value of keeping `null` is that it points you towards required action. The value of generating valid variables is that then you can run your query. I don't think we have enough data yet to change the current behavior, though the more folks who share their preference with us, the better.

**Closed by daniman** 2022-09-06 21:25 UTC
