### ISSUE TITLE
Apollo Sandbox Spam Fetching

### ISSUE THREAD

**Issue by Knight-H** [apollographql/apollo-studio-community#116] opened 2021-10-31 11:54 UTC
I'm not sure where should I post this, but I want to ask is this expected behavior? I plug in the explorer sandbox to an AWS AppSync schema. However, the workspace starts blinking (with auto update off), and there is spam polling on the schema.

![image](https://user-images.githubusercontent.com/19682720/139581808-0b912457-38aa-49d0-8509-725bcea7f66b.png)

It's really hogging in on my resources and I'm not sure how to fix the problem.

**Comment by mayakoneval** [comment] 2021-11-09 17:19
Hi @Knight-H, thanks for the bug report! It looks like each introspection request to these AWS appsync endpoints returns a slightly different schema. For example, the ordering of the directives in the response array might be different.

I could reproduce the bug you experienced with the spam polling because of this ^. That bug should be fixed if you are up to date with the studio version ("What's new in Studio" speaker icon at the top right -> update button at the bottom left of the modal)
![image](https://user-images.githubusercontent.com/14367451/140972938-2f070347-10de-4744-9218-ba8a5369eaf2.png)
. Thanks!

**Closed** 2021-11-09 17:19 UTC

**Comment by Knight-H** [comment] 2021-11-10 06:40
Great! Thank you very much! :DD
